["protostar.config"]
protostar_version = "0.1.0"

["protostar.project"]
libs_path = "lib"

["protostar.contracts"]
white_and_blacklist_account = [
    "./src/white_and_blacklist_account.cairo",
]
